# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-13 17:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20190913_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='dashboard.User'),
            preserve_default=False,
        ),
    ]
