# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-13 17:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_message_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='author',
        ),
    ]
